a = int(input("a = "))
b = int(input("b = "))
print("a + b = ", a + b, "\n")
print("a - b = ", a - b, "\n")
print("a / b = ", a // b, "\n")
print("Restul impartirii lui a la b = ", a % b, "\n")
print("a x b = ", a * b, "\n")
print("a ** b = ", a ** b, "\n")
